@startuml class

skinparam {
  Monochrome true
  Shadowing false
}
hide circle
hide empty members

title ドメインモデルのバージョン3

class "採用選考" as c1 {
  応募日付
  選考ステータス
  候補者情報
}

class "面接" as c2 {
  面接次数
  面接日付
  面接結果
}

class "採用担当者" as c3 {
  名前
}

class "採用ポジション" as c4 {
  採用ポジション名
  募集ステータス
}

class "面談" as c5 {
  面談日付
}

c1 "1" *-r- "0..n" c2
c2 "1" ---> "1..n" c3 : 面接担当者

c1 "1" *-d- "0..n" c5
c5 "1" -r-> "1..n" c3 : 面談担当者

c1 "0..n" --l-> "0..1" c4

note top of c1
・選考ステータスは「未募集」「選考中」「採用」「不採用」
・面談から始める場合、初期ステータスは「未募集」、応募日付はブランク
  (のちに選考に進んだ日付が応募日付になる)
・面接から始める場合、初期ステータスは「選考中」、応募日付は登録日付
end note

note top of c2
・選考ステータスが「選考中」以外のときには設定できない
・面接次数は1からインクリメントされる
・面接結果は「未評価」「合格」「不合格」
end note

note top of c4
・ステータスは
  「募集中」「募集終了」
end note

note bottom of c5
・面談は選考開始～終了の間に
  2回まで設定できる
end note

@enduml
